<?php

// TODO: Set up permissions
/**
 * Implements hook_permission(). 
 */
function handshake_feeds_permission() {

}

/**
 * Implements hook_menu().
 */
function handshake_feeds_menu() {
    $items = array();

    $items['admin/config/services/handshake_feeds'] = array(
        'title' => 'Handshake Feeds',
        'description' => 'Configure Handshake feeds settings.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('handshake_feeds_configure'),
        'access arguments' => array('access administration pages'),
        'file' => 'handshake_feeds.admin.inc',
      );

    return $items;
}